### ISSUE TITLE
Bits

### ISSUE THREAD

**Issue by nochinator** [StormDragon-64/Create-plus-plus#1]
Bits can be put on the mechanical press. They can be used to do some other recipes. To get some ideas of what they are and how they work see https://en.wikipedia.org/wiki/Stamping_(metalworking)
some ideas for things it could make are putting letters on blocks, gears, shafts, and cogs.

**Comment by Sshmoob** [comment]
I'm nowhere near good enough at modding to store text and then dynamically add that text to a model after it's been placed, so sorry, but maybe you can ask someone else to add this feature to their mod.

**Comment by nochinator** [comment]
I could try to code it, I just wanted to run it by you first before spending to much time on it. your fine with gpt code right?

**Comment by Sshmoob** [comment]
Also, there are mods that already allow you to do something similar, they just don't use Create.
